# Generated by Django 5.2.1 on 2025-06-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_bio_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
